$hyprlockDir = $HOME/.config/hypr/hyprlock

source = $hyprlockDir/themes/arctic-monsoon.conf
source = $hyprlockDir/colors/arctic-monsoon-colors.conf
source = $hyprlockDir/fonts/arctic-monsoon-font.conf

# Script Path
$music = $hyprlockDir/scripts/playerctlock.sh
$album = $hyprlockDir/scripts/hlock_mpris.sh
$battery = $hyprlockDir/scripts/battery.sh
$location = $hyprlockDir/scripts/location.sh
$weather = $hyprlockDir/scripts/weather.sh
