$hyprlockDir = $HOME/.config/hypr/hyprlock

source = $hyprlockDir/themes/one-forest.conf
source = $hyprlockDir/colors/one-forest-colors.conf
source = $hyprlockDir/fonts/style-2-font.conf

# Script Path
$music = $hyprlockDir/scripts/playerctlock.sh
$album = $hyprlockDir/scripts/hlock_mpris.sh
$battery = $hyprlockDir/scripts/battery.sh
$location = $hyprlockDir/scripts/location.sh
$weather = $hyprlockDir/scripts/weather.sh
