$hyprlockDir = $HOME/.config/hypr/hyprlock

source = $hyprlockDir/themes/style-2.conf
source = $hyprlockDir/colors/style-1-colors.conf
source = $hyprlockDir/fonts/style-1-font.conf

# Script Path
$music = $hyprlockDir/scripts/playerctlock.sh
$album = $hyprlockDir/scripts/hlock_mpris.sh
$battery = $hyprlockDir/scripts/battery.sh
$location = $hyprlockDir/scripts/location.sh
$weather = $hyprlockDir/scripts/weather.sh
