# Font Family
font_family JetBrainsMono Nerd Font

# Theme
include ./theme.conf

# Remove the close Confirmation Message
confirm_os_window_close 0

# Transparency (0 = fully transparent, 1 = opaque)
background_opacity 0.8

# Optional: Add blur effect (Linux only, requires compositor)
background_blur 2

# Edit Window Padding
window_padding_width 10 12

# Cursor Tail Effect
cursor_shape beam
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_shape block
cursor_stop_blinking_after 0
cursor_blink_interval 0

# Some Important Options

scrollback_lines 2000
copy_on_select yes
mouse_hide_wait 0
select_by_word_characters @-./_~?&=%+#a
enable_audio_bell no
bell_on_tab "🔔 "
remember_window_size  no
window_border_width 1pt
draw_minimal_borders yes
window_padding_width 10
inactive_text_alpha 0.6
hide_window_decorations yes
tab_bar_style powerline
url_style curly
sync_to_monitor no

